--SQL Advance Case Study
SELECT * FROM DIM_CUSTOMER
SELECT* FROM DIM_DATE
SELECT* FROM DIM_LOCATION
SELECT* FROM DIM_MANUFACTURER
SELECT * FROM DIM_MODEL
SELECT * FROM FACT_TRANSACTIONS




--Q1--BEGIN 
SELECT DISTINCT DL.State AS [STATE]
FROM FACT_TRANSACTIONS AS F
INNER JOIN DIM_LOCATION AS DL
ON F.IDLocation=DL.IDLocation
WHERE YEAR(F.DATE)>='2005'
GROUP BY DL.State
--Q1--END

--Q2--BEGIN
SELECT DM.Manufacturer_Name AS MANUFACTURER,State,Country,COUNT(DL.STATE) AS COUNT_PER_STATE
FROM DIM_LOCATION AS DL
INNER JOIN FACT_TRANSACTIONS AS F
ON DL.IDLocation = F.IDLocation
INNER JOIN DIM_MODEL AS DD
ON F.IDModel = DD.IDModel
INNER JOIN DIM_MANUFACTURER AS DM
ON DD.IDManufacturer = DM.IDManufacturer
WHERE Country ='US'
       AND
 DM.Manufacturer_Name='SAMSUNG'
 GROUP BY DM.Manufacturer_Name,State,Country
 ORDER BY COUNT_PER_STATE

 
--Q2--END

--Q3--BEGIN      
SELECT DISTINCT IDModel,ZipCode,State,COUNT(IDMODEL) AS [COUNT PER MODEL]
FROM FACT_TRANSACTIONS AS F
INNER JOIN DIM_LOCATION AS DL
ON F.IDLocation =DL.IDLocation
GROUP BY IDModel,ZipCode,State
ORDER BY [COUNT PER MODEL] DESC

--Q3--END

--Q4--BEGIN
SELECT TOP 1 F.IDModel,Model_Name,SUM(TOTALPRICE) AS TOTAL_PRICE
FROM FACT_TRANSACTIONS AS F
INNER JOIN DIM_MODEL AS DM
ON F.IDModel = DM.IDModel
GROUP BY F.IDModel,Model_Name
ORDER BY TOTAL_PRICE ASC
--Q4--END

--Q5--BEGIN
SELECT DM.Manufacturer_Name AS MANUFACTURER, D.IDModel,D.Model_Name AS MODEL,AVG(TOTALPRICE) AS AVERAGEPRICE,
 SUM(QUANTITY) AS TOTAL_QUANTITY
 FROM FACT_TRANSACTIONS AS F
 INNER JOIN DIM_MODEL AS D
 ON D.IDModel =F.IDModel
 INNER JOIN DIM_MANUFACTURER AS DM
 ON D.IDManufacturer = DM.IDManufacturer
 WHERE DM.Manufacturer_Name IN (SELECT TOP 5 DM.Manufacturer_Name AS MANUFACTURER
                  FROM DIM_MANUFACTURER AS DM
                  INNER JOIN DIM_MODEL AS D
                  ON DM.IDManufacturer =D.IDManufacturer
                  INNER JOIN FACT_TRANSACTIONS AS F
                  ON D.IDModel =F.IDModel
				  GROUP BY DM.IDManufacturer,DM.Manufacturer_Name
				  ORDER BY SUM(Quantity) DESC)
GROUP BY DM.Manufacturer_Name,D.IDModel,D.Model_Name 
ORDER BY AVERAGEPRICE DESC
 
 --Q5--END

--Q6--BEGIN
SELECT DC.IDCustomer,DC.Customer_Name AS CUSTOMER,YEAR(F.DATE) AS [YEAR],AVG(F.TotalPrice)AS AVERAGE_PRICE
FROM DIM_CUSTOMER AS DC
INNER JOIN FACT_TRANSACTIONS AS F
ON DC.IDCustomer = F.IDCustomer
WHERE YEAR(F.DATE) ='2009'
GROUP BY DC.IDCustomer ,DC.Customer_Name,YEAR(F.DATE)
HAVING AVG(F.TOTALPRICE)>'500'
ORDER BY AVERAGE_PRICE DESC
--Q6--END
	
--Q7--BEGIN 
SELECT* FROM(
SELECT TOP 5 DM.IDModel--DM.Model_Name AS MODEL,SUM(QUANTITY) AS QUANTITY
FROM DIM_MODEL AS DM
INNER JOIN FACT_TRANSACTIONS AS F
ON DM.IDModel = F.IDModel
WHERE YEAR(F.Date)=2008
GROUP BY DM.IDModel,DM.Model_Name
ORDER BY SUM(QUANTITY) DESC) AS T1

INTERSECT

SELECT* FROM(
SELECT TOP 5  DM.IDModel--,DM.Model_Name AS MODEL,F.Date AS DATE,SUM(QUANTITY) AS QUANTITY
FROM DIM_MODEL AS DM
INNER JOIN FACT_TRANSACTIONS AS F
ON DM.IDModel = F.IDModel
WHERE YEAR(F.Date)= 2009
GROUP BY DM.IDModel--,DM.Model_Name,F.Date
ORDER BY SUM(QUANTITY) DESC) AS T2

INTERSECT

SELECT* FROM(
SELECT TOP 5 DM.IDModel--,DM.Model_Name AS MODEL,SUM(QUANTITY) AS QUANTITY
FROM DIM_MODEL AS DM
INNER JOIN FACT_TRANSACTIONS AS F
ON DM.IDModel = F.IDModel
WHERE YEAR(F.Date)= 2010
GROUP BY DM.IDModel--,DM.Model_Name
ORDER BY SUM( QUANTITY) DESC	) AS T3

--Q7--END	
--Q8--BEGIN
SELECT* FROM(
SELECT TOP 10 DD.IDManufacturer AS ID,DD.Manufacturer_Name AS [NAME],YEAR(F.DATE) AS YEARS,SUM(TOTALPRICE) AS TOTAL_SALES,
DENSE_RANK()OVER (PARTITION BY YEAR(F.DATE) ORDER BY SUM( TOTALPRICE)) AS RANKS
FROM FACT_TRANSACTIONS AS F
INNER JOIN DIM_MODEL AS DM
ON F.IDModel = DM.IDModel
INNER JOIN DIM_MANUFACTURER AS DD
ON DM.IDManufacturer = DD.IDManufacturer
WHERE YEAR(F.DATE) IN (2009,2010)
GROUP BY DD.IDManufacturer ,DD.Manufacturer_Name,YEAR(F.DATE)
ORDER BY TOTAL_SALES) AS X
WHERE RANKS = 2

--Q8--END
--Q9--BEGIN
SELECT DM.Manufacturer_Name AS [NAME]--,YEAR(F.DATE) AS [YEAR],SUM(QUANTITY) AS QUANTITY
FROM DIM_MANUFACTURER AS DM
INNER JOIN DIM_MODEL AS DL
ON DM.IDManufacturer =DL.IDManufacturer
INNER JOIN FACT_TRANSACTIONS AS F
ON DL.IDModel = F.IDModel
WHERE YEAR(F.DATE) = 2010
GROUP BY DM.Manufacturer_Name--,YEAR(F.DATE)

EXCEPT


SELECT DM.Manufacturer_Name AS [NAME]--,YEAR(F.DATE) AS [YEAR],SUM(QUANTITY) AS QUANTITY
FROM DIM_MANUFACTURER AS DM
INNER JOIN DIM_MODEL AS DL
ON DM.IDManufacturer =DL.IDManufacturer
INNER JOIN FACT_TRANSACTIONS AS F
ON DL.IDModel = F.IDModel
WHERE YEAR(F.DATE) = 2009
GROUP BY DM.Manufacturer_Name--,YEAR(F.DATE)
 
--Q9--END

--Q10--BEGIN


/*SELECT TOP 10 DC.IDCustomer,DC.Customer_Name AS CUSTOMER,SUM(TOTALPRICE) AS TOTALSPEND
FROM DIM_CUSTOMER AS DC
INNER JOIN FACT_TRANSACTIONS AS F
ON DC.IDCustomer =F.IDCustomer
GROUP BY DC.IDCustomer,DC.Customer_Name
ORDER BY SUM(TOTALPRICE) DESC*/
SELECT  *,((AVG_SPENDS-LAG_PRICE)/LAG_PRICE) AS PERCENTAGE_PER_SPEND
FROM(
SELECT *,LAG(AVG_SPENDS,1) OVER(PARTITION BY ID ORDER BY YEAR) AS LAG_PRICE
FROM
(SELECT DC.IDCustomer AS ID,DC.Customer_Name AS CUSTOMER,YEAR(F.DATE)AS [YEAR],AVG(TOTALPRICE) AS AVG_SPENDS,SUM(QUANTITY) AS SUM_QUANTITY
FROM DIM_CUSTOMER AS DC
INNER JOIN FACT_TRANSACTIONS AS F
ON DC.IDCustomer = F.IDCustomer
WHERE DC.IDCustomer IN(SELECT TOP 10 DC.IDCustomer--,DC.Customer_Name AS CUSTOMER,SUM(TOTALPRICE) AS TOTALSPEND
                       FROM DIM_CUSTOMER AS DC
                       INNER JOIN FACT_TRANSACTIONS AS F
                       ON DC.IDCustomer =F.IDCustomer
                       GROUP BY DC.IDCustomer,DC.Customer_Name
                       ORDER BY SUM(TOTALPRICE) DESC
					   )
GROUP BY DC.IDCustomer,DC.Customer_Name,YEAR(F.DATE) 
) AS X
) AS Y

/*1- CALCULATE TOP 10 CUSTOMER AS PER TOTAL SPENDS-(SELECT TOP 10 DC.IDCustomer--,DC.Customer_Name AS CUSTOMER,SUM(TOTALPRICE) AS TOTALSPEND
                                                    FROM DIM_CUSTOMER AS DC
                                                    INNER JOIN FACT_TRANSACTIONS AS F
                                                    ON DC.IDCustomer =F.IDCustomer
                                                    GROUP BY DC.IDCustomer,DC.Customer_Name
                                                    ORDER BY SUM(TOTALPRICE) DESC)

  2- FETCH THE AVG SPEND AND TOTAL QUNATTITY OF THOSE CUSTOMERS-( SELECT DC.IDCustomer AS ID,DC.Customer_Name AS CUSTOMER,YEAR(F.DATE)AS [YEAR],AVG(TOTALPRICE) AS AVG_SPENDS,SUM(QUANTITY) AS SUM_QUANTITY
FROM DIM_CUSTOMER AS DC
INNER JOIN FACT_TRANSACTIONS AS F
ON DC.IDCustomer = F.IDCustomer
WHERE DC.IDCustomer IN(SELECT TOP 10 DC.IDCustomer--,DC.Customer_Name AS CUSTOMER,SUM(TOTALPRICE) AS TOTALSPEND
                       FROM DIM_CUSTOMER AS DC
                       INNER JOIN FACT_TRANSACTIONS AS F
                       ON DC.IDCustomer =F.IDCustomer
                       GROUP BY DC.IDCustomer,DC.Customer_Name
                       ORDER BY SUM(TOTALPRICE) DESC
					   )
GROUP BY DC.IDCustomer,DC.Customer_Name,YEAR(F.DATE) )

 3-FIND THE LAG PRICE OF AVG PRICE TO FURTHER CALCULATE PRCENTAGE-
                           SELECT *,LAG(AVG_SPENDS,1) OVER(PARTITION BY ID ORDER BY YEAR) AS LAG_PRICE
FROM
(SELECT DC.IDCustomer AS ID,DC.Customer_Name AS CUSTOMER,YEAR(F.DATE)AS [YEAR],AVG(TOTALPRICE) AS AVG_SPENDS,SUM(QUANTITY) AS SUM_QUANTITY
FROM DIM_CUSTOMER AS DC
INNER JOIN FACT_TRANSACTIONS AS F
ON DC.IDCustomer = F.IDCustomer
WHERE DC.IDCustomer IN(SELECT TOP 10 DC.IDCustomer--,DC.Customer_Name AS CUSTOMER,SUM(TOTALPRICE) AS TOTALSPEND
                       FROM DIM_CUSTOMER AS DC
                       INNER JOIN FACT_TRANSACTIONS AS F
                       ON DC.IDCustomer =F.IDCustomer
                       GROUP BY DC.IDCustomer,DC.Customer_Name
                       ORDER BY SUM(TOTALPRICE) DESC
					   )
GROUP BY DC.IDCustomer,DC.Customer_Name,YEAR(F.DATE) 
) AS X          )
  
  4- CALCULATE PERCENTAGE BY USING FORMULA-
                 SELECT  *,((AVG_SPENDS-LAG_PRICE)/LAG_PRICE) AS PERCENTAGE_PER_SPEND
FROM(
SELECT *,LAG(AVG_SPENDS,1) OVER(PARTITION BY ID ORDER BY YEAR) AS LAG_PRICE
FROM
(SELECT DC.IDCustomer AS ID,DC.Customer_Name AS CUSTOMER,YEAR(F.DATE)AS [YEAR],AVG(TOTALPRICE) AS AVG_SPENDS,SUM(QUANTITY) AS SUM_QUANTITY
FROM DIM_CUSTOMER AS DC
INNER JOIN FACT_TRANSACTIONS AS F
ON DC.IDCustomer = F.IDCustomer
WHERE DC.IDCustomer IN(SELECT TOP 10 DC.IDCustomer--,DC.Customer_Name AS CUSTOMER,SUM(TOTALPRICE) AS TOTALSPEND
                       FROM DIM_CUSTOMER AS DC
                       INNER JOIN FACT_TRANSACTIONS AS F
                       ON DC.IDCustomer =F.IDCustomer
                       GROUP BY DC.IDCustomer,DC.Customer_Name
                       ORDER BY SUM(TOTALPRICE) DESC
					   )
GROUP BY DC.IDCustomer,DC.Customer_Name,YEAR(F.DATE) 
) AS X
) AS Y


             )*/
			 
               











--Q10--END
	